before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: HIJDyQRF25pch0YU8JVNMxbmc/R3nkMlVR1tEhuVDx3AgxftY7L5/4vIGcbDLGFxJ97kXA113SIC46SA3LEvonIh+OqNMgER2ZRqG+6UtxTGAKViFT8Z5lhFdydI4LqBlH4+rviUwkzRXPjP3/RgYbC/PmZhEFir17KkYF6ikm+aYHqO9AW8781gnP9Rk8cKOByxUHuJ1d/KuxVrwNIPNU6oHE3lL0IpOaYvDhPKxVCCkcF1N08SwS/vIjGn53ikKmL5ZQ5ARQt2BnA8W1MBmNokQdmtgk+FgVOU1gTXxSQPQ5DJYDfSsOw+TtPJ6g5R8rAtB/Ma0cg4l8xW63IEJ0EB1AvJGgECtxzzF0Xzbv2ZLjERwRztMhpPj9P0flty3MmXDELxSPrhnJONVu8847jw5uFtgptpW2hvCgZctpU3O0SfPAYWykT/xo0pqZtuunhkvB0WbSBDfCnt2NULxwq9Fr1W63awUVleW1pStElNEXg1Qia8RulKQcpuPr86O0ghZXSeG7mfRzk+AfRjp/IJn49ntnlRv5Fg6NiVBZXfGO2rdQYj3awf5/oP0UbkyPgEvN/5PpUpsEHzr2Z/8wqD3+y/cm34S06+wjO4fgGOB58jR8HrlgMXaiBvcQDWjVokFDLyK5PzihVKqbrOe0NeedPdz7N1tVXRskzhEBk= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
